version: '3.8'

services:
  spring-app:
    image: inheecho/test-v6  # Spring Boot 애플리케이션 이미지
    container_name: spring-app-test
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - spring-net
    volumes:
      - /home/ec2-user/logs:/logs

  redis:
    image: redis:latest
    container_name: redis-container
    depends_on:
      - spring-app
    ports:
      - "6379:6379"
    networks:
      - spring-net

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/:/etc/nginx/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - spring-app
    networks:
      - spring-net
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge
volumes:
  logs:
