spring:
  profiles:
    active: docker

  config:
    import: "classpath:application-secret.yml"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: redis-container
      #      host: localhost
      port: '6379'
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: inhees98@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  server:
    tomcat:
      max-swallow-size: 15MB
      max-http-post-size: 15MB

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==


springdoc:
  swagger-ui:
    #    groups-order: DESC
    #    tags-sorter: alpha
    #    operations-sorter: method
    path: /swagger-ui/index.html
  api-docs:
    path: /v1/api-docs