spring:
  config:
    import: "classpath:application-secret.yml"

  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: '6379'
    type: redis

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==


springdoc:
  swagger-ui:
#    groups-order: DESC
#    tags-sorter: alpha
#    operations-sorter: method
    path: /swagger-ui/index.html
  api-docs:
    path: /v1/api-docs