spring:
  profiles:
    active: docker

#  config:
#    import: "file:/app/config/application-secret.yml"
#    import: "classpath:application-secret.yml"


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: redis-container
      #      host: localhost
      port: '6379'
    type: redis

  mail:
    host: smtp.gmail.com
    port: 587
    username: inhees98@gmail.com
    password: xxac auuo gvqe kouf
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  kafka:
    bootstrap-servers: 15.164.228.135:9092, 54.180.56.87:9092, 13.124.83.93:9092

  datasource:
    url: jdbc:mysql://db-capstone.ckklth9vipd7.ap-northeast-2.rds.amazonaws.com:3306/capstone
    username: admin
    password: Abcd123~
    driver-class-name: com.mysql.cj.jdbc.Driver


  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  server:
    tomcat:
      max-swallow-size: 15MB
      max-http-post-size: 15MB

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==


springdoc:
  swagger-ui:
    #    groups-order: DESC
    #    tags-sorter: alpha
    #    operations-sorter: method
    path: /swagger-ui/index.html
  api-docs:
    path: /v1/api-docs


naver:
  client-key: 4nqjg17mp4
  client-secret-key: 6soiuZVRnR7eETaDKQmIf5x9ktGr9D8TnvaavJOg

public:
  api:
    service-key: =351qYfh59jJHQGLGCTf2af0is6PVkCNFKEfj2%2FdXVQKfBWFGg1%2BiSHbG6D6edWitwcgQ%2FKV6P82xpCPpM%2FD4sg%3D%3D